import cv2

CAMERA = cv2.VideoCapture(0)
CAMERA.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
CAMERA.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

CAMERA_FRAME_RATIO = 720 / 1280
TERMINAL_FONT_RATIO = 9 / 20
RATIO = CAMERA_FRAME_RATIO * TERMINAL_FONT_RATIO

ASCII_CHARS = " .,:=+*#%&@"
